# main text of home
name: Matt Mawer
bio: Researcher - Education specialist - Tea drinker

# twitter summary info
#description:

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: https://www.linkedin.com/in/mattmawer/

url: http://mattmawer.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# if you don't have any of social below, comment the line
# facebook: 
# twitter: 
# google: 
# instagram: 
# pinterest: 
linkedin: mattmawer/
# youtube: 
# spotify: 
github: mattmawer/
# lastfm: 
# stackoverflow:
# quora: 
# reddit: 
# medium: 
# vimeo: 
email: matt@mattmawer.co.uk

authors:
    matt:
        name: Matt Mawer
        bio: Education researcher - Methodologist - Tea drinker
        external-image: false
        picture: assets/images/profile.jpg
        twitter:

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, about, or blog, comment the *projects* configs below
projects: true
about: true
blog: true

# do you want to show the "tags" inside the posts?
show-tags: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com
